=== alaagawish/XML-API-Labs/Lab3/build/classes/lab3/demo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="Person" type="PersonType"/>
	<xs:complexType name="PersonType">
		<xs:sequence>
			<xs:element name="Name" type="NameType"/>
			<xs:element name="Address" type="AddressType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="kind" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="NameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AddressType">
		<xs:sequence>
			<xs:element name="Number" type="xs:unsignedInt"/>
			<xs:element name="Street" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== alaagawish/XML-API-Labs/Lab3/src/lab3/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="demo.xsd">
	<Name>omer</Name>
	<Address>
		<Number>123</Number>
		<Street>haram</Street>
	</Address>
	<Address>
		<Number>456</Number>
		<Street>HARAM</Street>
	</Address>
</Person>
